### ISSUE TITLE
디비 문제는 어떻게 할까요?

### ISSUE THREAD

**Issue by serohero** [serohero/swengineering#1]
입출력 시스템으로 할까요, 아님 데이터베이스를 따로 사용할까요?

**Comment by chlthgP37** [comment]
mysql 디비로 하는 건 어떨까요?

**Comment by serohero** [comment]
그럼 제가 디비 맡아서 진행하도록 하겠습니다!

**Comment by kimikimi247** [comment]
데이터베이스 이름을 마이노트로 하는 거 어때요?

**Comment by serohero** [comment]
네 그럽 mynote를 데이터베이스 이름으로, 총 3개 테이블: address, todolist, appointment 만들겠습니다

**Comment by kimikimi247** [comment]
넹 알겠습니다. 확인하였습니다

**Comment by chlthgP37** [comment]
네 알겠습니다.
