### ISSUE TITLE
테스트는 j유닛으로 하는거죠? 

### ISSUE THREAD

**Issue by kimikimi247** [serohero/swengineering#8]
우리 자바로 짰으니까 제이유닛으로 테스트 해야 되는거죠?
테스팅 기대된다
일일하게 대입하는 거 아니고 프로그램 쓰는 테스팅 처음이라 기대된다.

**Comment by chlthgP37** [comment]
어 저도 기대되요 제이유닛으로 테스트 하는거 맞아용

**Comment by serohero** [comment]
몰랐네요 좋은 정보 감사합니다

**Comment by kimikimi247** [comment]
넵 그럼 제이유닛으로 하는 거 이제 다 알게 되신걸로합니다~~
